name: faso_electronic
description: Application e-commerce pour l'électronique au Burkina Faso
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI & Utils
  fluttertoast: ^8.2.4
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets (on va les ajouter plus tard)
  # assets:
  #   - assets/images/
  #   - assets/icons/